In [1]:
import numpy as np

def initialize_messages(L, init_val=1.0):
    """ Initialize the messages to a constant value (e.g., 1). """
    messages = np.full((L, L, 4), init_val)  # 4 directions (N, E, S, W)
    return messages

def update_messages(L, J, beta, messages):
    """ Perform a single iteration of message updates. """
    new_messages = np.zeros_like(messages)
    for i in range(L):
        for j in range(L):
            for direction in range(4):
                # Determine neighbors based on direction
                ni, nj = neighbor_index(i, j, direction, L)
                # Sum contributions from all but the direction of interest
                m_sum = 0
                for back_dir in range(4):
                    if back_dir == (direction + 2) % 4:
                        continue
                    back_ni, back_nj = neighbor_index(i, j, back_dir, L)
                    m_sum += messages[back_ni, back_nj, (back_dir + 2) % 4]
                
                new_messages[i, j, direction] = np.tanh(beta * J * m_sum)
    return new_messages

def neighbor_index(i, j, direction, L):
    """ Return the neighbor index for direction N=0, E=1, S=2, W=3. """
    if direction == 0:  # North
        return (i - 1) % L, j
    elif direction == 1:  # East
        return i, (j + 1) % L
    elif direction == 2:  # South
        return (i + 1) % L, j
    elif direction == 3:  # West
        return i, (j - 1) % L

def loopy_belief_propagation(L, J, beta, iterations=30):
    messages = initialize_messages(L)
    for _ in range(iterations):
        messages = update_messages(L, J, beta, messages)
    return messages

# Example usage:
L = 5  # lattice size
J = 1   # interaction strength
beta = 0.44  # inverse temperature
messages = loopy_belief_propagation(L, J, beta)
print(messages)

[[[0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]]

 [[0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]]

 [[0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]]

 [[0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]
  [0.76649394 0.76649394 0.76649394 0.76649394]]

 [[0.76649394 0.76649394 0.76649